version: "3.9"

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    restart: unless-stopped

  web:
    build: .
    image: simple_blog
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      WEB_CONCURRENCY: 1
      REDIS_ENDPOINT: redis
      REDIS_PASSWORD: '' # only used in production
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - db
      - redis

  sidekiq:
    image: simple_blog
    command: bash -c "bundle exec sidekiq"
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    environment:
      REDIS_ENDPOINT: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - db
      - redis
      - web # need to send request to web
