apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-blog
spec:
  selector:
    matchLabels:
      app: simple-blog
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-blog
    spec:
      volumes:
        - name: puma-sock
          emptyDir: {}
      containers:
        - name: nginx
          image: kinlong/simple_blog_nginx:master-20210605-07d5b8a
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/run/puma
              name: puma-sock
        - name: rails-web
          image: kinlong/simple_blog_rails:20210610-master-07d5b8a
          command: ["bundle", "exec", "puma", "-C", "config/puma.rb", "-b", "unix:///var/run/puma/puma.sock"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: RAILS_LOG_TO_STDOUT
              value: "1"
          envFrom:
            - secretRef:
                name: simple-blog
          volumeMounts:
            - mountPath: /var/run/puma
              name: puma-sock
        # TODO: this can be in another deployment as this doesn't need to be exposed with service
        - name: rails-sidekiq
          image: kinlong/simple_blog_rails:20210610-master-07d5b8a
          command: ["bundle", "exec", "sidekiq"]
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: simple-blog
