apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-blog-sidekiq
spec:
  selector:
    matchLabels:
      app: simple-blog
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-blog
    spec:
      containers:
        - name: rails-sidekiq
          image: kinlong/simple_blog_rails:20210618-master-0d8e37e
          command: ["bundle", "exec", "sidekiq"]
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: simple-blog
            - configMapRef:
                name: simple-blog-rails
