apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-blog
spec:
  selector:
    matchLabels:
      app: simple-blog
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-blog
    spec:
      volumes:
        - name: puma-sock
          emptyDir: {}
      containers:
        - name: nginx
          image: kinlong/simple_blog_nginx:master-20210605-07d5b8a
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/run/puma
              name: puma-sock
          startupProbe:
            httpGet:
              path: /posts
              port: 80
              scheme: HTTP
            failureThreshold: 50
            periodSeconds: 5
        - name: rails-web
          image: kinlong/simple_blog_rails:20210613-master-a9ab38a
          command: ["bundle", "exec", "puma", "-C", "config/puma.rb", "-b", "unix:///var/run/puma/puma.sock"]
          imagePullPolicy: Always
          # TODO: do I need port if I have unix socket?
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: RAILS_LOG_TO_STDOUT
              value: "1"
            - name: RAILS_MIN_THREADS
              value: "1"
            - name: RAILS_MAX_THREADS
              value: "2"
          envFrom:
            - secretRef:
                name: simple-blog
            - configMapRef:
                name: simple-blog-rails
          volumeMounts:
            - mountPath: /var/run/puma
              name: puma-sock
